# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Alejandro Mizrahi Cengarle
tagline:          'Personal research webpage'
description:      'PhD Candidate at TSE'
url:              alejandromizrahi.github.io
baseurl:          /

author:
  name:           'Alejandro Mizrahi Cengarle'
  
paginate:         5

# Custom vars
version:          2.1.0
