# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Alejandro Mizrahi Cengarle
tagline:          'Personal research webpage'
description:      'PhD Candidate at TSE'
url:              https://alejandromizrahi.github.io
baseurl:          ""
theme: jekyll-theme-hyde

author:
  name:           'Alejandro Mizrahi Cengarle'
  
paginate:         5
